# 1. 문제 정의
    - 머신러닝으로 어떤 것을 해결할 것인가를 정하기

X_train : 훈련용 문제데이터, y_train : 훈련용 정답 데이터
X_test : 평가용 문제데이터, y_test : 평가용 정답 데이터

과대적합 : 규칙을 너무 자세히 정해서 특정한 것만 맞추는 현상
과소적합 : 규칙을 너무 대충 정해서 아무 것도 못맞추는 현상


훈련용 데이터 : 모델이 학습(훈련)을 하는데 사용하는 데이터
평가용 데이터 : 모델이 평가를 하는데 사용하는 데이터


훈련용 데이터의 점와 평가용 데이터의 점수를 비교

knn.score(X_train, y_train) : 훈련용 점수 확인
knn.score(X_test, y_test) : 평가용 점수 확인

일반적으로 훈련용 데이터의 점수는 평가용 데이터의 점수보다 높게 나온다
훈련용 데이터는 모델이 이미 한번 확인한 데이터

1. 모델1의 결과
train score : 0.9
test score : 0.8
모델이 학습이 잘 되었는가?(모델이 일반화가 잘 되었는가?)
과대적합의 가능성이 높음(규칙이 너무 train만 맞추게 되어 있다)

2. 모델2의 결과
train score : 0.85
test score : 0.85
일반화가 되었을 가능성이 높음(규칙이 적당히 설계되어서 test를 잘 맞춘다)


3. 모델3의 결과
train score : 0.8
test score : 0.7
과소적합 되었을 가능성이 높음(규칙이 너무 없어서 train도 test도 못맞춘다)


* 교차 검증
    - 하나의 데이터를 여러개 나눠서 여러번 평가를 진행하는 방법
    - 하나의 데이터를 여러개의 데이터처럼 사용할 수

In [1]:
# iris(붓꽃) 데이터를 활용해서 머신러닝 7단계 진행하기
# 교차검증 활용하기

# 2. 데이터 수집
    - 정의된 문제를 해결하기 위한 데이터 모으기

In [2]:
import numpy as np
import pandas as pd

from sklearn.datasets import load_iris

data = load_iris(as_frame=True)

data

{'data':      sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
 0                  5.1               3.5                1.4               0.2
 1                  4.9               3.0                1.4               0.2
 2                  4.7               3.2                1.3               0.2
 3                  4.6               3.1                1.5               0.2
 4                  5.0               3.6                1.4               0.2
 ..                 ...               ...                ...               ...
 145                6.7               3.0                5.2               2.3
 146                6.3               2.5                5.0               1.9
 147                6.5               3.0                5.2               2.0
 148                6.2               3.4                5.4               2.3
 149                5.9               3.0                5.1               1.8
 
 [150 rows x 4 columns],
 'target': 0     

In [3]:
data.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [4]:
# 머신러닝의 초기는 발달된 통계(수학)
# 초기 모델들은 수학 공식으로 이루어진 경우가 많음
# y = ax + b
# y : 궁금한 값, 정답데이터의 역할과 비슷
# X : 제공하는 값, 문제데이터의 역할과 비슷

# y는 소문자, X는 대문자인 이유
# 


# X는 대문자 : X는 주로 2차원 이상의 데이터
# y는 소문자 : y는 주로 1차원 데이터

X = data['data']
y = data['target']

# 3. 데이터 전처리
    - 수집된 데이터를 학습할 수 있는 형태로 처리하기

In [5]:
# value_counts() : 컬럼안에서 값의 갯수 세기
# fillna() : 결측기 채우기
# info() : 데이터 전반적으로 확인하기

In [6]:
# iris 데이터는 sklearn에서 제공해주는 예제용 데이터라 추가 처리할게 없다.

# 4. 탐색적 데이터 분석
    - 데이터의 특징, 생김새 확인하기

In [7]:
import matplotlib.pyplot as plt
import seaborn as sns

In [8]:
# 최근에는 많이 줄어들었다
# 필수로 진행하는 단계는 아님

# 5. 모델 선택 및 하이퍼 파라미터 튜닝
    - 데이터에 어울리는 모델 찾기
    - 모델 세부 기능 설정하기

In [9]:
# 머신러닝에서는 sklearn
# 딥러닝에서는 tensorflow

In [10]:
# 데이터 나누기 : train과 test 분리하기
# 5단계에서 하는 이유 : 확실하게 3,4단계가 끝났기 때문

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state = 2)

# 6. 학습
    - 모델이 데이터에서 규칙 찾기

In [11]:
# model.fit(X_train, y_train)

In [12]:
from sklearn.neighbors import KNeighborsClassifier 
knn =  KNeighborsClassifier()

print(np.shape(X_train))
print(np.shape(X_test))
print(np.shape(y_train))
print(np.shape(y_test))

knn.fit(X_train, y_train)

(105, 4)
(45, 4)
(105,)
(45,)


KNeighborsClassifier()

# 7. 평가 및 예측
    - 평가 : 만들어진 규칙이 어마나 정확한지 알아보기
    - 예측 : 만들어진 규칙 사용해보기

In [13]:
# model.predict(X_test)
# model.score(X_test, y_test)

In [14]:
pre = knn.predict(X_test)

# 분류한 꽃의 품종 인덱싱을 통해 출력
pre

array([0, 0, 2, 0, 0, 2, 0, 2, 2, 0, 0, 0, 0, 0, 1, 1, 0, 1, 2, 1, 1, 1,
       2, 1, 1, 0, 0, 2, 0, 2, 2, 0, 1, 2, 1, 0, 2, 1, 1, 2, 1, 1, 2, 1,
       0])

In [20]:
# 교차 검증
# 데이터를 5개(보편적으로)로 나눠서 훈련과 평가를 반복하며 여러번 결과를 확인하는 방법
# 여러번 결과를 확인하면 모델의 평가
from sklearn.model_selection import cross_val_score
score = cross_val_score(knn, X_train, y_train, cv = 5)
score

array([0.9047619 , 1.        , 1.        , 0.85714286, 0.95238095])

In [21]:
score.mean()

0.9428571428571428

In [22]:
# 교차 검증
test_score = cross_val_score(knn, X_test, y_test, cv = 5)
test_score

array([0.88888889, 0.88888889, 0.88888889, 0.88888889, 1.        ])

In [23]:
test_score.mean()

0.9111111111111111